---
# Install Elasticsearch

- name: Import the Elasticsearch public GPG key into rpm
  rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Create a yum repository for Elasticsearch
  template: src=elastic.repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install Elasticsearch package
  yum: name=elasticsearch-1.1.1 state=present

- name: Configure Elasticsearch - disable dynamic scripts
  lineinfile: "dest=/etc/elasticsearch/elasticsearch.yml line='script.disable_dynamic: true' state=present"

- name: Configure Elasticsearch - Restrict outside access to instance
  lineinfile: "dest=/etc/elasticsearch/elasticsearch.yml regexp='# discovery.zen.ping.multicast.enabled: false' line='discovery.zen.ping.multicast.enabled: false'"

- name: Configure Elasticsearch - Restrict outside access
  lineinfile: "dest=/etc/elasticsearch/elasticsearch.yml regexp='# network.host: 192.168.0.1' line='network.host: localhost'"

- name: Start Elasticsearch and enable on boot
  service: name=elasticsearch state=started enabled=yes