---
- name: Download the Kibana tarball
  command: wget https://download.elasticsearch.org/kibana/kibana/kibana-3.0.1.tar.gz
  args:
    chdir: /home/vagrant/
    creates: /home/vagrant/kibana-3.0.1

- name: Extract the Kibana archive
  unarchive: src=/home/vagrant/kibana-3.0.1.tar.gz dest=/home/vagrant/ copy=no

- name: Configure Kibana
  template: src=config.js.j2 dest=/home/vagrant/kibana-3.0.1/config.js owner=root group=root mode=0644

- name: Copy Kibana installation into a new directory - create directory
  command: mkdir -p /var/www/kibana3

- name: Copy Kibana installation into the new directory
  raw: sudo cp -R /home/vagrant/kibana-3.0.1/* /var/www/kibana3/